### ISSUE TITLE
Ambiguity in method resolution when multiple presenters are under same package name 

### ISSUE THREAD

**Issue by NikolaDespotoski** [Omega-R/OmegaMoxy#33]
If you have multiple presenters under same package name 
eg.
`com.my.presenters.package.MyPresenter0`
`com.my.presenters.package.MyPresenter1`
`com.my.presenters.package.MyPresenter2`

IDE is getting confused which of the generated `providePresenter` functions to import, because they are typed.

**Comment by anton-knyazev** [comment]
Hello,

I'm pleased to inform you that the issue regarding ambiguous imports of the `providePresenter` function due to multiple presenters within the same package has been resolved. We implemented unique presenter names, such as `provideExamplePresenter`, to ensure clear identification and usage of these functions.

Your initiative in raising this task was greatly appreciated, as it helped us address a critical part of our project's functionality. Thank you for bringing this to our attention!
